[package]
name = "dino-park-packs"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4", features = ["postgres", "uuidv07"] }
actix-web = "1.0"
actix-cors = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
dotenv = "0.9"
uuid = { version = "0.7", features = ["serde", "v4"] }
log = "0.4"
env_logger = "0.6"
failure = "0.1"
diesel-derive-enum = { version = "0.4", features = ["postgres"] }