[package]
name = "dino-park-packs"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

[features]
default = []
localuserscope = ["dino_park_gate/localuserscope"]

[dependencies]
cis_client = { git = "https://github.com/fiji-flo/cis_client-rust", branch = "0.1.5", version = "0.1.5" }
cis_profile = { git = "https://github.com/fiji-flo/cis_profile-rust", branch = "0.1.3", version = "0.1.3", features = ["graphql", "aws", "vendored"] }
dino_park_gate = { git = "https://github.com/fiji-flo/dino-park-gate", branch = "0.1.1", version = "0.1.1" }
diesel = { version = "1.4", features = ["postgres", "uuidv07", "r2d2"] }
actix-web = "1.0"
actix-cors = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
dotenv = "0.9"
uuid = { version = "0.7", features = ["serde", "v4"] }
log = "0.4"
env_logger = "0.6"
failure = "0.1"
diesel-derive-enum = { version = "0.4", features = ["postgres"] }
futures = "0.1"
r2d2 = "0.8"
config = "0.9"
chrono = "0.4"
