apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.name }}-cron
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 * * * * "
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.name }}-cron
            image: curl
            args:
            - /bin/sh
            - -c
            - curl -X POST localhost:8085/internal/expire/all
          restartPolicy: OnFailure